import 'package:flutter/material.dart';

const double dp0 = 0.0;
const double dp1 = 1.0;
const double dp2 = 2.0;
const double dp3 = 3.0;
const double dp4 = 4.0;
const double dp5 = 5.0;
const double dp6 = 6.0;
const double dp8 = 8.0;
const double dp10 = 10.0;
const double dp12 = 12.0;
const double dp14 = 14.0;
const double dp16 = 16.0;
const double dp20 = 20.0;
const double dp24 = 24.0;
const double dp28 = 28.0;
const double dp32 = 32.0;
const double dp36 = 36.0;
const double dp40 = 40.0;
const double dp48 = 48.0;
const double dp56 = 56.0;
const double dp64 = 64.0;

const double radiusValue2 = 2.0;
const double radiusValue4 = 4.0;
const double radiusValue8 = 8.0;
const double radiusValue10 = 10.0;
const double radiusValue12 = 12.0;
const double radiusValue16 = 16.0;
const double radiusValue20 = 20.0;
const double radiusValue24 = 24.0;
const double radiusValue28 = 28.0;
const double radiusValue32 = 32.0;

const Radius radius2 = Radius.circular(radiusValue2);
const Radius radius4 = Radius.circular(radiusValue4);
const Radius radius8 = Radius.circular(radiusValue8);
const Radius radius10 = Radius.circular(radiusValue10);
const Radius radius12 = Radius.circular(radiusValue12);
const Radius radius16 = Radius.circular(radiusValue16);
const Radius radius20 = Radius.circular(radiusValue20);
const Radius radius24 = Radius.circular(radiusValue24);
const Radius radius28 = Radius.circular(radiusValue28);
const Radius radius32 = Radius.circular(radiusValue32);

const BorderRadius borderRadius2 = BorderRadius.all(radius2);
const BorderRadius borderRadius4 = BorderRadius.all(radius4);
const BorderRadius borderRadius8 = BorderRadius.all(radius8);
const BorderRadius borderRadius10 = BorderRadius.all(radius10);
const BorderRadius borderRadius12 = BorderRadius.all(radius12);
const BorderRadius borderRadius16 = BorderRadius.all(radius16);
const BorderRadius borderRadius20 = BorderRadius.all(radius20);
const BorderRadius borderRadius24 = BorderRadius.all(radius24);
const BorderRadius borderRadius28 = BorderRadius.all(radius28);
const BorderRadius borderRadius32 = BorderRadius.all(radius32);
